#include "game_tools.h"
#include "main.h"
// Lookup table will be generated by the macro
#define X(id, fullname, tool_price, tool_type) {fullname, tool_price, tool_type, NULL},
tool_info_t tools[TOOLS_COUNT] = {
	TOOLS_TABLE
};
#undef X

tools_t current_tool;

void game_tools_init (void) {
	char temptext[64];
	char canonical[16];
	for (uint8_t i=0; i<TOOLS_COUNT; i++) {
		make_canonical(canonical, tools[i].name);
		sprintf(temptext, "rom:/images/tools/%s.ci4.sprite", canonical);
		tools[i].sprite = sprite_load(temptext);
	}
	current_tool = TOOL_NONE;
}

void game_tools_close (void) {
	for (uint8_t i=0; i<TOOLS_COUNT; i++) {
		sprite_free(tools[i].sprite);
	}
}
