// tools.h

#ifndef GAMEJAM2025_GAME_TOOLS_H
#define GAMEJAM2025_GAME_TOOLS_H

#include <libdragon.h>

#define TOOLS_PRICE_DEFAULT 100

typedef enum {
	TOOLS_TYPE_NONE,
	TOOLS_TYPE_USABLE,
	TOOLS_TYPE_HOLD,
	TOOLS_TYPE_STORE,
	TOOLS_TYPE_PERM,
	TOOLS_TYPE_COUNT,
} tools_type_t;

// Put new tools here
#define TOOLS_TABLE \
	X(TOOL_NONE,	"None",			TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_NONE)	\
	X(TOOL_BONE,	"Bone",			TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_USABLE)	\
	X(TOOL_BROOM,	"Broom",		TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_HOLD)	\
	X(TOOL_BRUSH,	"Brush",		TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_HOLD)	\
	X(TOOL_GLOVES,	"Gloves",		TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_PERM)	\
	X(TOOL_IRON,	"Iron",			TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_STORE)	\
	X(TOOL_BULB,	"Light Bulb",	TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_USABLE)	\
	X(TOOL_MOP,		"Mop",			TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_HOLD)	\
	X(TOOL_PAINT,	"Paint",		TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_USABLE)	\
	X(TOOL_PEN,		"Pen",			TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_HOLD)	\
	X(TOOL_PLUNGER,	"Plunger",		TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_HOLD)	\
	X(TOOL_WRENCH,	"Wrench",		TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_HOLD)	\
	X(TOOL_REMOTE,	"Tv Remote",	TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_PERM)	\
	X(TOOL_VACUUM,	"Vacuum",		TOOLS_PRICE_DEFAULT,	TOOLS_TYPE_STORE)	\


// Enum table will be generated by the above
#define X(id, tool_name, tool_price, tool_type) id,
typedef enum {
	TOOLS_TABLE
	TOOLS_COUNT
} tools_t;
#undef X

typedef struct {
	const char *name;
	uint16_t price;
	tools_type_t type;
	sprite_t *sprite;
} tool_info_t;

extern tool_info_t tools[TOOLS_COUNT];
extern tools_t current_tool;

void game_tools_init (void);
void game_tools_close (void);

#endif
