// state.c
#include "state.h"

// Lookup table will be generated by the macro
#define X(id, init_func, move_func, draw_func, close_func) {init_func, move_func, draw_func, close_func},
state_table_row_t states[STATE_COUNT] = {
	STATE_TABLE
};
#undef X

// Current state
state_id_t current_state = STATE_GAME;

// Use this to switch from one state to another
void state_switch (state_id_t new_state) {
	states[current_state].close_func();
	current_state = new_state;
	states[current_state].init_func();
}
