// state.h

#ifndef GAMEJAM2025_STATE_H
#define GAMEJAM2025_STATE_H

#include <libdragon.h>
#include "intro.h"
#include "menu.h"

// Put new game states here
#define STATE_TABLE \
    X(STATE_INTRO, intro_init, intro_move, intro_draw, intro_close) \
    X(STATE_MENU, menu_init, menu_move, menu_draw, menu_close) \

// Enum table will be generated by the above
#define X(id, init_func, move_func, draw_func, close_func) id,
typedef enum {
	STATE_TABLE
	STATE_COUNT
} state_id_t;
#undef X

typedef struct state_table_row_s {
	void(*init_func)(void);
	void(*move_func)(float);
	void(*draw_func)(void);
	void(*close_func)(void);
} state_table_row_t;

void state_switch (state_id_t new_state);

extern state_id_t current_state;
extern state_table_row_t states[STATE_COUNT];

#endif
